import { Movie } from "./types";

// Simulated demo catalogue standing in for a real data provider (e.g. TMDB
// filtered to AU release dates). Titles are invented so the app never shows
// fabricated dates/times against a real film. Swap this module for a real
// fetch from TMDB (or similar) without touching anything downstream — every
// consumer only depends on the `Movie` shape.

export const SEED_MOVIES: Movie[] = [
  {
    id: "mv-01",
    title: "The Long Ember",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-09-24",
    runtimeMinutes: 128,
    genres: ["Drama", "Thriller"],
    synopsis: "A bushfire investigator uncovers a decade-old cover-up in a small Victorian timber town.",
    posterColor: "from-orange-500/70 to-red-900/80",
  },
  {
    id: "mv-02",
    title: "Harbour Lights",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-10-01",
    runtimeMinutes: 104,
    genres: ["Romance", "Comedy"],
    synopsis: "Two rival ferry captains in Sydney Harbour are forced to share a route — and a houseboat.",
    posterColor: "from-sky-500/70 to-blue-900/80",
  },
  {
    id: "mv-03",
    title: "Midnight Ferry",
    releaseType: "Limited Release",
    releaseDate: "2026-10-08",
    runtimeMinutes: 96,
    genres: ["Mystery"],
    synopsis: "A late-night commuter realises the same six passengers have ridden with her for a month.",
    posterColor: "from-indigo-600/70 to-slate-900/80",
  },
  {
    id: "mv-04",
    title: "Red Centre Static",
    releaseType: "Film Festival",
    releaseDate: "2026-09-18",
    runtimeMinutes: 88,
    genres: ["Documentary"],
    synopsis: "A season embedded with a remote outback radio station fighting to stay on air.",
    posterColor: "from-amber-600/70 to-rose-950/80",
  },
  {
    id: "mv-05",
    title: "Paper Suburb",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-10-15",
    runtimeMinutes: 112,
    genres: ["Drama"],
    synopsis: "A council clerk discovers her entire street was drawn on a map to trap land speculators — and never actually built.",
    posterColor: "from-emerald-600/70 to-teal-950/80",
  },
  {
    id: "mv-06",
    title: "Southerly",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-10-22",
    runtimeMinutes: 121,
    genres: ["Action", "Thriller"],
    synopsis: "A storm-chasing salvage crew races a cool change down the coast to reach a stranded rig.",
    posterColor: "from-cyan-600/70 to-slate-950/80",
  },
  {
    id: "mv-07",
    title: "The Understudy's Understudy",
    releaseType: "Limited Release",
    releaseDate: "2026-09-20",
    runtimeMinutes: 99,
    genres: ["Comedy"],
    synopsis: "Third-string cover for a third-string cover in a doomed regional theatre production of Hamlet.",
    posterColor: "from-fuchsia-600/70 to-purple-950/80",
  },
  {
    id: "mv-08",
    title: "Bones of the Reef",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-11-05",
    runtimeMinutes: 134,
    genres: ["Adventure", "Drama"],
    synopsis: "A marine biologist and a salvage diver clash over a wreck that's either a heritage site or a fortune.",
    posterColor: "from-teal-500/70 to-blue-950/80",
  },
  {
    id: "mv-09",
    title: "Quiet Hours",
    releaseType: "Film Festival",
    releaseDate: "2026-09-16",
    runtimeMinutes: 76,
    genres: ["Drama"],
    synopsis: "A hospital night-shift cleaner and a new father share the only two hours of quiet in the building.",
    posterColor: "from-slate-500/70 to-zinc-950/80",
  },
  {
    id: "mv-10",
    title: "Static Caravan",
    releaseType: "Limited Release",
    releaseDate: "2026-10-29",
    runtimeMinutes: 91,
    genres: ["Horror"],
    synopsis: "A caretaker closing a coastal holiday park for winter keeps finding one cabin still occupied.",
    posterColor: "from-red-700/70 to-black/80",
  },
  {
    id: "mv-11",
    title: "The Cartographer's Daughter",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-11-19",
    runtimeMinutes: 118,
    genres: ["Adventure", "Family"],
    synopsis: "A surveyor's daughter follows her late father's unfinished map of the Blue Mountains.",
    posterColor: "from-lime-600/70 to-emerald-950/80",
  },
  {
    id: "mv-12",
    title: "Nightshift at the Big Merino",
    releaseType: "Limited Release",
    releaseDate: "2026-09-27",
    runtimeMinutes: 83,
    genres: ["Comedy", "Drama"],
    synopsis: "A roadside attraction's overnight security guard becomes the town's accidental radio confessor.",
    posterColor: "from-pink-500/70 to-rose-950/80",
  },
  {
    id: "mv-13",
    title: "Departure Board",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-12-03",
    runtimeMinutes: 109,
    genres: ["Drama", "Romance"],
    synopsis: "Two strangers keep missing the same regional train and, eventually, each other.",
    posterColor: "from-violet-600/70 to-indigo-950/80",
  },
  {
    id: "mv-14",
    title: "Salt Flat Radio",
    releaseType: "Film Festival",
    releaseDate: "2026-09-30",
    runtimeMinutes: 94,
    genres: ["Documentary", "Music"],
    synopsis: "A pirate radio station broadcasts from a dry lake bed to an audience of land-speed racers.",
    posterColor: "from-yellow-500/70 to-orange-950/80",
  },
  {
    id: "mv-15",
    title: "The Last Milk Bar",
    releaseType: "Standard Theatrical",
    releaseDate: "2026-11-26",
    runtimeMinutes: 101,
    genres: ["Comedy"],
    synopsis: "Three siblings have thirty days to decide whether to sell the family milk bar or fight the mall next door.",
    posterColor: "from-orange-400/70 to-amber-950/80",
  },
];
